### ISSUE TITLE
Add properties to customize frame option

### ISSUE THREAD

**Issue by milazzo-g** [enginious-dev/fjwt#3]
add boolean property to:

- prevents headers from being added to the response and to 
- specify to allow any request that comes from the same origin to frame this application

property should be inside:

```
fjwt:
  # other props
  frame-options:
    same-origin: {true|false [default true]}
    disabled: {true|false [default true]}
```
